### ISSUE TITLE
Support the HEAD and OS/2 tables

### ISSUE THREAD

**Issue by TsundereBug** [TsundereBug/Scolor#1]
Something for someone more experienced with byte wizardry can do

**Comment by TsundereBug** [comment]
HEAD: [https://www.microsoft.com/typography/otspec/head.htm](https://www.microsoft.com/typography/otspec/head.htm)
OS/2: [https://www.microsoft.com/typography/otspec/os2.htm](https://www.microsoft.com/typography/otspec/os2.htm)

**Comment by oschrenk** [comment]
I had some nice experiences when dealing with binary data using scodec.

**Comment by TsundereBug** [comment]
This project is based off of its custom ByteAllocator, mainly because it fits the project snugly. However, there should be enough example code for tables to figure out the transition from scodec to this system :)

**Comment by TsundereBug** [comment]
This has been implemented
