### ISSUE TITLE
Make the mapping in the segmented format of EncodingRecord more readable

### ISSUE THREAD

**Issue by TsundereBug** [TsundereBug/Scolor#12]
@EdgeCaseBerg seems like something for you :)

[https://www.microsoft.com/typography/otspec/cmap.htm#format12](https://www.microsoft.com/typography/otspec/cmap.htm#format12)

This is taking the ranges and mapping them specifically.

**Comment by EdgeCaseBerg** [comment]
@TsundereBug I'm at work now but I'll take a look at it once I'm home!

**Comment by TsundereBug** [comment]
Fixed by #13
