### ISSUE TITLE
Support the SBIX table

### ISSUE THREAD

**Issue by TsundereBug** [TsundereBug/Scolor#5]
Microsoft docs for clarity: [https://www.microsoft.com/typography/otspec/sbix.htm](https://www.microsoft.com/typography/otspec/sbix.htm)

The real docs are at [https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6sbix.html](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6sbix.html)

**Comment by gerd2002** [comment]
I am done with my Hacktoberfest ;)

**Comment by TsundereBug** [comment]
implemented in 486a2afff469aeab34186255f6ca6dd2d44da5b8
